### ISSUE TITLE
Present the architecture and purpose of the system

### ISSUE THREAD

**Issue by BastienFaivre** [AmandaStromdahl/algorithms#52] opened 2022-03-06 08:40 UTC
This is referring to point 3.2.1.1 of the assignment

**Comment by PersonligaPersson** [comment] 2022-03-06 20:37
This issue is a duplicate of issue 13. It was solved in PR #13 . I'll close this issue for now. If you disagree we can talk about it tomrorow.

**Closed by PersonligaPersson** 2022-03-06 20:37 UTC
Labels: documentation, duplicate
